server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:rock_paper_scissors_db
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
